# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftLint

on:
  workflow_dispatch: # 手動実行を許可

jobs:
  lint:
    runs-on: macos-latest # SwiftLint を実行するため macOS を指定
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '5.9' # 必要に応じてバージョンを変更

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: swiftlint  --config .swiftlint.yaml
